# Generated by Django 5.0.1 on 2024-01-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entpName', models.TextField(null=True)),
                ('itemName', models.TextField(null=True, unique=True)),
                ('itemSeq', models.IntegerField(null=True)),
                ('efcyQesitm', models.TextField(null=True)),
                ('useMethodQesitm', models.TextField(null=True)),
                ('atpnWarnQesitm', models.TextField(null=True)),
                ('atpnQesitm', models.TextField(null=True)),
                ('intrcQesitm', models.TextField(null=True)),
                ('seQesitm', models.TextField(null=True)),
                ('depositMethodQesitm', models.TextField(null=True)),
                ('openDe', models.DateTimeField(null=True)),
                ('updateDe', models.DateField(null=True)),
                ('itemImage', models.TextField(null=True)),
                ('bizrno', models.IntegerField(null=True)),
            ],
        ),
    ]
